// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoFhqPYrpVaHXDcpw7kBYtnm1u78ZexwQ',
    appId: '1:388644559702:web:b9da99b7fb9623acb114f7',
    messagingSenderId: '388644559702',
    projectId: 'miaged-3c16e',
    authDomain: 'miaged-3c16e.firebaseapp.com',
    storageBucket: 'miaged-3c16e.appspot.com',
    measurementId: 'G-C8ESENWL7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe28MgHMvmH8zUr0epiOfK3vYqSo_DQhc',
    appId: '1:388644559702:android:8205c3b6d01b3ad6b114f7',
    messagingSenderId: '388644559702',
    projectId: 'miaged-3c16e',
    storageBucket: 'miaged-3c16e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp0VjPAIP86c0vAOKJ61GawfGyf28qtdw',
    appId: '1:388644559702:ios:256db2ed1745d0bfb114f7',
    messagingSenderId: '388644559702',
    projectId: 'miaged-3c16e',
    storageBucket: 'miaged-3c16e.appspot.com',
    iosClientId: '388644559702-5ogvafcug1j7a5qtkg36r1fesh52mv70.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp0VjPAIP86c0vAOKJ61GawfGyf28qtdw',
    appId: '1:388644559702:ios:256db2ed1745d0bfb114f7',
    messagingSenderId: '388644559702',
    projectId: 'miaged-3c16e',
    storageBucket: 'miaged-3c16e.appspot.com',
    iosClientId: '388644559702-5ogvafcug1j7a5qtkg36r1fesh52mv70.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
